apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-appstudio/internal-services/config/crd?ref=3d850c7d5a8660db9d7e3830aa39f3742eac5244

namespace: release-service
